src/Entity/ProfileItem.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

abstract class ProfileItem
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type:'integer')]
    protected int $id;

    #[ORM\Column(type:"string", length:255, nullable:true)]
    protected ?string $title;

    #[ORM\Column(type:"string", length:255, nullable:true)]
    protected ?string $url;

    #[ORM\Column(type:"string", length:255, nullable:true)]
    protected ?string $github;

    #[ORM\Column(name:"url_label", type:"string", length:255, nullable:true)]
    protected ?string $urlLabel;

    #[ORM\Column(name:"github_label", type:"string", length:255, nullable:true)]
    protected ?string $githubLabel;

    #[ORM\Column(type:"text", nullable:true)]
    protected ?string $description;

    #[ORM\Column(name:"city", type:"string", length:255, nullable:true)]
    protected ?string $city;

    #[ORM\Column(name:"started_at", type:"date", nullable:true)]
    protected ?\DateTime $startedAt;

    #[ORM\Column(name:"stoped_at", type:"date", nullable:true)]
    protected ?\DateTime $stopedAt;

    /**
     * @return string|null
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * @param string|null $city
     */
    public function setCity(?string $city): void
    {
        $this->city = $city;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function getUrlLabel(): ?string
    {
        return $this->urlLabel;
    }

    /**
     * @return string|null
     */
    public function getGithub(): ?string
    {
        return $this->github;
    }

    /**
     * @param string|null $github
     */
    public function setGithub(?string $github): void
    {
        $this->github = $github;
    }

    /**
     * @return string|null
     */
    public function getGithubLabel(): ?string
    {
        return $this->githubLabel;
    }

    /**
     * @param string|null $githubLabel
     */
    public function setGithubLabel(?string $githubLabel): void
    {
        $this->githubLabel = $githubLabel;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function getStartedAt(): ?\DateTime
    {
        return $this->startedAt;
    }

    public function getStopedAt(): ?\DateTime
    {
        return $this->stopedAt;
    }

    /**
     * Dates formattées au format "depuis x" ou "x - y"
     * TODO dans twig
     */
    public function getFormattedDate(): string
    {
        if(!$this->getStopedAt()) {
            // pas finis : "depuis x"
            $output = 'Depuis '.strftime('%b %Y', $this->getStartedAt()->getTimestamp());
        } else {
            // finis : "x à y"
            $output =   strftime('%b %Y', $this->getStartedAt()->getTimestamp()).' - '
                . strftime('%b %Y', $this->getStopedAt()->getTimestamp());
        }

        return $output;
    }

    /**
     * durée au format : "x ans, y mois"
     * TODO dans twig
     */
    public function getFormattedDuration(): string
    {
        // La durée
        $duration = $this->getStartedAt()->diff($this->getStopedAt() ?: new \DateTime(), true);

        // formatage
        $output = '';

        foreach (['y' => 'an(s)', 'm' => 'mois'] as $intervalField => $translation) {
            if ($duration->$intervalField) {
                $output .= $duration->$intervalField.' '.$translation.' ';
            }
        }

        return $output;
    }

}

templates/app/sections/about.html.twig
<section class="content" id="about">

    <p class="about">{{ profile.about }}</p>
    <p class="about mb-3">A cela s'allie, mon amour pour les mots et leur agencement. J'aime prendre du recul sur une situation donnée, la clarifier avec des mots simples et des phrases accessibles. </p>

    <hr>

    <h5>Aptitudes</h5>
    <div class="container">
        {% for softskill in profile.softSkills %}
            <p class="soft-skills">{{ softskill.title }}</p>
        {% endfor %}
    </div>

</section>

templates/app/sections/cv.html.twig
<section class="content" id="cv">
    <div class="d-print-none">
        <div class="d-flex justify-content-end"><a href="javascript: void(0);" onclick="window.print();"><i class="fas fa-print"></i> Version PDF ou Impression de mon CV !</a></div>
    </div>

    <h3>Compétences web</h3>
    <hr>
    <ul id="col">

        {% for skill in profile.skills %}

            <li class="">{{ skill.title }}</li>

        {% endfor %}

    </ul>

    <h3>Expériences</h3>
    <hr>

    {% for experience in profile.experiences %}
        <div class="row">
            <div class="col-md-4">
                <div class="mb-3 badge bg-warning text-white"><i class="fas fa-calendar-alt text-white"></i>&nbsp; {{ experience.formattedDate }}</div>
            </div>

            <div class="col-md-8">
                <div class="d-flex justify-content-between">
                    <strong><p>{{ experience.title }}</p></strong>
                    {% if experience.company %}
                        <p class=""><i class="fas fa-building pink-color small"></i><a href="https://www.ifs73.fr/">{{ experience.company }}</a> <p class="city small"> - &nbsp; {{ experience.city }}</p> </p>
                    {% endif %}
                    {% if experience.url %}
                        <a class="blue-color" href="{{ experience.url }}"> <i class="fas fa-link"></i> {{ experience.urlLabel }}</a>
                    {% endif %}
                    {% if experience.github %}
                        <a class="blue-color" href="{{ experience.github }}"><i class="fab fa-github-alt"></i> {{ experience.githubLabel }}</a>
                    {% endif %}
                </div>
                <p>{{ experience.description|raw }}</p>

            </div>
        </div>
    {% endfor %}

    <h3>Formations</h3>
    <hr>

    {% for education in profile.educations %}

        <div class="row">
            <div class="col-md-4">
                <div class="mb-3 badge bg-warning text-white"><i class="fas fa-calendar-alt text-white"></i>&nbsp;{{ education.formattedDate }}</div>
            </div>

            <div class="col-md-8 d-flex justify-content-start">

                <strong><p class="">{{ education.title }}</p></strong>
                <p>  </p>
                <p class="mx-4"><i class="fas fa-school small"></i> {{ education.school }}

                <p class="city small"> - &nbsp {{ education.city }}</p>

            </div>
        </div>

    {% endfor %}

</section>

templates/app/sections/header.html.twig
<section class="content" id="header">

    <div class="container">

        <div class="card card-identity border-light col-md-4" style="max-width: 20rem;">
            <div class="card-body card-body-identity">
                <h6 class="card-subtitle mb-2"><i class="fas fa-at"></i> {{ profile.email }}</h6>
                <p class="card-text mb-2"><i class="fas fa-mobile-alt"></i> {{ profile.telephone }}</p>
                <p class="card-text mb-2"><i class="fas fa-map-marker-alt"></i>  {{ profile.city }}</p>
                <a href="#" class="card-link social-icon mt-2"><i class="fab fa-linkedin"></i></a>
                <a href="#" class="card-link social-icon mt-2"><i class="fab fa-github"></i></a>
                <a href="#" class="card-link social-icon mt-2"><i class="fab fa-twitter-square"></i></a>
                <span class="btn btn-success btn-sm card-link d-flex align-items-end"><i class="fas fa-toggle-on"></i>&nbsp;Disponible</span>
            </div>
        </div>

        <div class="label text-center col-md-8">
            <h1 class="">{{ profile.name }}</h1>
            <h2 class="h4 label-cv">{{ profile.jobTitle }}</h2>
        </div>

    </div>

</section>

templates/app/sections/realisations.html.twig
<section class="content" id="realisations">

    <h3 class="text-center">Mes réalisations</h3>

    <hr>

    <h5 class="subtitle"> Développement web </h5>

    <div class="container">
        {% for realisation in profile.realisations %}
                <div class="card card-realisations my-2">
                    <div class="card-body">
                        <h4 class="card-title">{{ realisation.title }}</h4>
                        <h6 class="card-subtitle my-2 text-muted fw-bolder">{{ realisation.technology }}</h6>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="{{ realisation.url }}" class="card-link"><i class="fas fa-link"></i></a>
                        <a href="{{ realisation.github }}" class="card-link"><i class="fab fa-github-alt"></i></a>
                    </div>
                </div>
        {% endfor %}
    </div>

    <hr>
    <h5 class="subtitle"> Rédaction </h5>

    <p>A Compléter ... </p>

    <hr>
    <h5 class="subtitle"> Analyses de données </h5>

    <p>A Compléter ... </p>

</section>